---
-   name: Add OpenJDK repository
    apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
        filename: openjdk
        update_cache: yes

-   name: Install OpenJDK
    apt:
        name:
            - openjdk-8-jre
        state: present
        update_cache: yes